# Android Gradle CircleCI 2.0 configuration
#
version: 2
jobs:
    build:
        branches:
            only:
            - final
        docker:
            - image: circleci/android:api-25-alpha

        working_directory: ~/code
        environment:
            JVM_OPTS: -Xmx3200m
        steps:
            - checkout
            - run:
                name: Create android licenses directory if it doesn't exist
                command: mkdir -p /opt/android/sdk/licenses
            - run:
                name: Transfer Android SDK licenses
                command: cp licenses/android-sdk-license /opt/android/sdk/licenses/
            - restore_cache:
                key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
            - run:
                name: Download Dependencies
                command: ./gradlew androidDependencies
            - save_cache:
                paths:
                    - ~/.gradle
                    key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
            - run:
                name: Run Tests
                command: ./gradlew lint test
            - store_artifacts:
                path: app/build/reports
                destination: reports
            - store_test_results:
                path: app/build/test-results

